/**
 * payTo single-source refactor: RESPONSE-BYTE-IDENTITY golden.
 *
 * tests/fixtures/payto-refactor.golden.json was generated by running THIS file
 * with UPDATE_PAYTO_GOLDEN=1 on a clean checkout of origin/main 153d1f3, BEFORE
 * any refactor change (this file + the fixture were the only additions). The
 * refactor must reproduce every byte: status, every header (sorted) and the
 * raw body of every unpaid 402 / OPTIONS for all 13 paid routes, plus the
 * discovery surfaces, in each payment-env mode production can be in:
 *   - PAY_TO unset / PAY_TO = config (lower-case, production today) /
 *     PAY_TO = config in EIP-55 case with surrounding whitespace
 *   - CDP mode (facilitator-synced) and local mode (no CDP keys)
 *   - Solana rail off and on (Base entry + Solana entry)
 * Changing a payTo value (a cut-over) MUST regenerate this fixture in the same
 * commit; the fixture diff must then be only old -> new address swaps.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { getAddress } from "viem";
import { resetSolanaRailForTests } from "@/lib/solana-rail";
import payto from "../config/payto.json";
import { captureDiscovery, captureRoutes } from "./helpers/capture";
import { installBothFacilitators, setCdp, stubSolanaOn } from "./helpers/solana-env";

const GOLDEN = path.join(__dirname, "fixtures", "payto-refactor.golden.json");

// The env values production may carry (PAY_TO equal to the config value).
const PAY_TO_ENV: Record<string, string | undefined> = {
  "PAY_TO unset": undefined,
  "PAY_TO=config (lower-case)": payto.base.payTo,
  "PAY_TO=config (EIP-55 case, padded)": `  ${getAddress(payto.base.payTo)} \n`,
};

async function captureMode(payTo: string | undefined, solana: boolean) {
  resetSolanaRailForTests();
  vi.unstubAllEnvs();
  if (solana) stubSolanaOn();
  if (payTo !== undefined) vi.stubEnv("PAY_TO", payTo);
  setCdp(true);
  const cdp = await captureRoutes();
  setCdp(false);
  const local = await captureRoutes();
  return { cdp, local };
}

async function captureAll() {
  const out: Record<string, unknown> = {};
  for (const [name, payTo] of Object.entries(PAY_TO_ENV)) {
    for (const solana of [false, true]) {
      out[`${name} | solana ${solana ? "on" : "off"}`] = await captureMode(payTo, solana);
    }
  }
  vi.unstubAllEnvs();
  out.discovery = await captureDiscovery();
  return JSON.stringify(out, null, 1) + "\n";
}

describe("payTo refactor: 402 + discovery bytes identical to pre-refactor main (153d1f3)", () => {
  beforeEach(() => {
    installBothFacilitators();
    vi.spyOn(console, "warn").mockImplementation(() => {});
  });
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.restoreAllMocks();
    resetSolanaRailForTests();
  });

  if (process.env.UPDATE_PAYTO_GOLDEN === "1") {
    it("writes the golden fixture (pre-refactor main only)", async () => {
      writeFileSync(GOLDEN, await captureAll());
    });
    return;
  }

  it("golden covers 13 routes x 6 env modes x {cdp, local}", () => {
    expect(existsSync(GOLDEN)).toBe(true);
    const g = JSON.parse(readFileSync(GOLDEN, "utf8"));
    const modes = Object.keys(g).filter((k) => k !== "discovery");
    expect(modes).toHaveLength(6);
    for (const m of modes) {
      for (const side of ["cdp", "local"]) {
        const routes = new Set(Object.keys(g[m][side]).map((k) => k.split(" ")[1]));
        expect(routes.size).toBe(13);
      }
    }
  });

  it("every captured byte is identical", async () => {
    const golden = readFileSync(GOLDEN, "utf8");
    const now = await captureAll();
    expect(now.length).toBe(golden.length);
    expect(now).toBe(golden);
  });
});
