/**
 * Flag-off byte-identity: with HP_XRPL_ENABLED unset (or anything other than
 * exactly "true" with a valid HP_XRPL_PAYTO), every 402 / OPTIONS / discovery
 * surface must be byte-identical to origin/main.
 *
 * tests/fixtures/x402-flag-off.golden.json was generated by running THIS file
 * with UPDATE_GOLDEN=1 on a clean checkout of origin/main (fc7e5f6), before any
 * XRPL code existed. Both CDP mode (facilitator-synced withX402 challenge) and
 * local mode (no CDP keys, lib/x402-server.ts builder) are covered.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { installFacilitatorMock } from "./helpers/facilitator-mock";
import { CDP_ENV, captureDiscovery, captureRoutes } from "./helpers/capture";

const GOLDEN = path.join(__dirname, "fixtures", "x402-flag-off.golden.json");

async function captureAll() {
  vi.unstubAllEnvs();
  vi.stubEnv("CDP_API_KEY_ID", CDP_ENV.CDP_API_KEY_ID);
  vi.stubEnv("CDP_API_KEY_SECRET", CDP_ENV.CDP_API_KEY_SECRET);
  const cdp = await captureRoutes();
  vi.stubEnv("CDP_API_KEY_ID", "");
  vi.stubEnv("CDP_API_KEY_SECRET", "");
  const local = await captureRoutes();
  return { cdp, local, discovery: await captureDiscovery() };
}

/** Env variants that must all be treated as flag OFF. */
const OFF_VARIANTS: Record<string, Record<string, string>> = {
  "unset": {},
  "flag=TRUE (case)": { HP_XRPL_ENABLED: "TRUE", HP_XRPL_PAYTO: "__VALID__" },
  "flag=1": { HP_XRPL_ENABLED: "1", HP_XRPL_PAYTO: "__VALID__" },
  "flag=' true' (whitespace)": { HP_XRPL_ENABLED: " true", HP_XRPL_PAYTO: "__VALID__" },
  "flag=true, payTo missing": { HP_XRPL_ENABLED: "true" },
  "flag=true, payTo bad checksum": { HP_XRPL_ENABLED: "true", HP_XRPL_PAYTO: "__BADSUM__" },
  "flag=true, payTo is an EVM address": { HP_XRPL_ENABLED: "true", HP_XRPL_PAYTO: "0x5b32c973596078a967562ca652761404f19be0e9" },
  "flag=true, mainnet without facilitator URL": { HP_XRPL_ENABLED: "true", HP_XRPL_PAYTO: "__VALID__", HP_XRPL_NETWORK: "xrpl:0" },
  "flag=true, unknown network": { HP_XRPL_ENABLED: "true", HP_XRPL_PAYTO: "__VALID__", HP_XRPL_NETWORK: "xrpl:9" },
};

describe("flag off: byte-identical to origin/main", () => {
  beforeEach(() => {
    installFacilitatorMock();
    vi.spyOn(console, "warn").mockImplementation(() => {});
  });
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.restoreAllMocks();
  });

  if (process.env.UPDATE_GOLDEN === "1") {
    it("writes the golden fixture (run on origin/main only)", async () => {
      const all = await captureAll();
      writeFileSync(GOLDEN, JSON.stringify(all, null, 1) + "\n");
    });
    return;
  }

  it("golden fixture exists", () => {
    expect(existsSync(GOLDEN)).toBe(true);
  });

  for (const [name, env] of Object.entries(OFF_VARIANTS)) {
    it(`env ${name}`, async () => {
      const golden = JSON.parse(readFileSync(GOLDEN, "utf8"));
      const { validTestAddress, badChecksumAddress } = await import("./helpers/xrpl-addresses");
      const resolved = Object.fromEntries(
        Object.entries(env).map(([k, v]) => [
          k,
          v === "__VALID__" ? validTestAddress(7) : v === "__BADSUM__" ? badChecksumAddress(7) : v,
        ]),
      );
      const all = await (async () => {
        vi.unstubAllEnvs();
        for (const [k, v] of Object.entries(resolved)) vi.stubEnv(k, v);
        vi.stubEnv("CDP_API_KEY_ID", CDP_ENV.CDP_API_KEY_ID);
        vi.stubEnv("CDP_API_KEY_SECRET", CDP_ENV.CDP_API_KEY_SECRET);
        const cdp = await captureRoutes();
        vi.stubEnv("CDP_API_KEY_ID", "");
        vi.stubEnv("CDP_API_KEY_SECRET", "");
        const local = await captureRoutes();
        return { cdp, local, discovery: await captureDiscovery() };
      })();
      // Whole-object string compare = byte-identical bodies + headers + status.
      expect(JSON.stringify(all)).toBe(JSON.stringify(golden));
    });
  }
});
