/**
 * Flag-off byte-identity: with the Solana rail off (HP_SOLANA_ENABLED unset,
 * or anything other than exactly "true" together with HP_SOLANA_PAYTO equal to
 * the pinned payout address), every 402 / OPTIONS / discovery surface must be
 * byte-identical to origin/main.
 *
 * tests/fixtures/x402-flag-off.golden.json was generated by running THIS file
 * with UPDATE_GOLDEN=1 on a clean checkout of origin/main (fc7e5f6), before any
 * Solana code existed (lib/ and app/ untouched; only this harness + vitest
 * added). Both CDP mode (facilitator-synced withX402 challenge) and local mode
 * (no CDP keys, lib/x402-server.ts builder) are covered.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { installFacilitatorMock } from "./helpers/facilitator-mock";
import { CDP_ENV, captureDiscovery, captureRoutes } from "./helpers/capture";

const GOLDEN = path.join(__dirname, "fixtures", "x402-flag-off.golden.json");

async function captureWith(env: Record<string, string>) {
  vi.unstubAllEnvs();
  for (const [k, v] of Object.entries(env)) vi.stubEnv(k, v);
  vi.stubEnv("CDP_API_KEY_ID", CDP_ENV.CDP_API_KEY_ID);
  vi.stubEnv("CDP_API_KEY_SECRET", CDP_ENV.CDP_API_KEY_SECRET);
  const cdp = await captureRoutes();
  vi.stubEnv("CDP_API_KEY_ID", "");
  vi.stubEnv("CDP_API_KEY_SECRET", "");
  const local = await captureRoutes();
  return { cdp, local, discovery: await captureDiscovery() };
}

const PINNED = "BjY98A6dS3GGLZdz2zHy8wK7XAwnQgNhCc66mfmBTRPz";

/** Env variants that must all be treated as flag OFF. */
const OFF_VARIANTS: Record<string, Record<string, string>> = {
  "unset": {},
  "payTo set, flag unset": { HP_SOLANA_PAYTO: PINNED },
  "flag=TRUE (case)": { HP_SOLANA_ENABLED: "TRUE", HP_SOLANA_PAYTO: PINNED },
  "flag=1": { HP_SOLANA_ENABLED: "1", HP_SOLANA_PAYTO: PINNED },
  "flag=' true' (whitespace)": { HP_SOLANA_ENABLED: " true", HP_SOLANA_PAYTO: PINNED },
  "flag=false": { HP_SOLANA_ENABLED: "false", HP_SOLANA_PAYTO: PINNED },
  "flag=true, payTo missing": { HP_SOLANA_ENABLED: "true" },
  "flag=true, payTo empty": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: "" },
  "flag=true, payTo one char edited": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: PINNED.slice(0, -1) + "Q" },
  "flag=true, payTo truncated": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: PINNED.slice(0, -1) },
  "flag=true, payTo lower-cased": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: PINNED.toLowerCase() },
  "flag=true, payTo with trailing space": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: `${PINNED} ` },
  "flag=true, payTo is another valid pubkey (USDC mint)": {
    HP_SOLANA_ENABLED: "true",
    HP_SOLANA_PAYTO: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  },
  "flag=true, payTo is the Base EVM payTo": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: "0x5b32c973596078a967562ca652761404f19be0e9" },
  "flag=true, network devnet (mainnet only)": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: PINNED, HP_SOLANA_NETWORK: "solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1" },
  "flag=true, network garbage": { HP_SOLANA_ENABLED: "true", HP_SOLANA_PAYTO: PINNED, HP_SOLANA_NETWORK: "solana" },
};

describe("flag off: byte-identical to origin/main", () => {
  beforeEach(() => {
    installFacilitatorMock();
    vi.spyOn(console, "warn").mockImplementation(() => {});
  });
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.restoreAllMocks();
  });

  if (process.env.UPDATE_GOLDEN === "1") {
    it("writes the golden fixture (run on origin/main only)", async () => {
      const all = await captureWith({});
      writeFileSync(GOLDEN, JSON.stringify(all, null, 1) + "\n");
    });
    return;
  }

  it("golden fixture exists", () => {
    expect(existsSync(GOLDEN)).toBe(true);
  });

  for (const [name, env] of Object.entries(OFF_VARIANTS)) {
    it(`env ${name}`, async () => {
      const golden = readFileSync(GOLDEN, "utf8");
      const all = await captureWith(env);
      // Whole-object string compare = byte-identical bodies + headers + status.
      expect(JSON.stringify(all, null, 1) + "\n").toBe(golden);
    });
  }
});
