#!/usr/bin/env node
/**
 * License gate: fails on GPL/AGPL/LGPL, proprietary, non-commercial,
 * UNLICENSED/UNKNOWN/custom licenses anywhere in the installed dependency tree.
 * Runs as the first step of `npm test` (so it bites locally and anywhere tests
 * run); a GitHub Actions workflow can call `npm test` later.
 *
 *   npm test                         # license-check (prod + dev) then vitest
 *   npm run license-check            # prod + dev tree
 *   npm run license-check -- --production
 *   npm run license-check -- --start=../other-checkout
 *   npm run notices                  # regenerate THIRD-PARTY-NOTICES (prod tree)
 *
 * Policy lives in scripts/license-policy.json (allowlist, denylist, pinned
 * exceptions with reasons). Uses license-checker-rseidelsohn to read the tree.
 */
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const require = createRequire(import.meta.url);
const checker = require("license-checker-rseidelsohn");

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const policy = JSON.parse(readFileSync(path.join(repo, "scripts/license-policy.json"), "utf8"));
const argv = process.argv.slice(2);
const args = new Set(argv);
// --start=DIR scans another checkout (e.g. to prove the gate fails on an old tree).
const root = path.resolve(argv.find((a) => a.startsWith("--start="))?.slice(8) ?? repo);
const production = args.has("--production") || args.has("--notices");

const allow = new Set(policy.allow);
const denyRe = new RegExp(policy.deny.map((d) => d.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"), "i");
const exceptions = new Map(policy.exceptions.map((e) => [e.package, e]));
/** Exact name match, or a trailing-* prefix match ("@img/sharp-libvips-*"). */
const findException = (name) =>
  exceptions.get(name) ?? policy.exceptions.find((e) => e.package.endsWith("*") && name.startsWith(e.package.slice(0, -1)));

/** Tiny SPDX evaluator: OR = any branch allowed, AND = all allowed, parens. */
function spdxAllowed(expr) {
  const tokens = expr.replace(/\(/g, " ( ").replace(/\)/g, " ) ").trim().split(/\s+/);
  let i = 0;
  const atom = () => {
    const t = tokens[i++];
    if (t === "(") { const v = orExpr(); i++; return v; }
    const id = t.replace(/\*$/, "").replace(/\+$/, ""); // "MIT*" = guessed from LICENSE file
    return allow.has(id);
  };
  const andExpr = () => { let v = atom(); while (tokens[i] === "AND") { i++; v = atom() && v; } return v; };
  const orExpr = () => { let v = andExpr(); while (tokens[i] === "OR") { i++; v = andExpr() || v; } return v; };
  try { const v = orExpr(); return i >= tokens.length && v; } catch { return false; }
}

const pkgs = await new Promise((resolve, reject) =>
  checker.init(
    { start: root, production, excludePrivatePackages: true, customFormat: args.has("--notices") ? { name: "", version: "", licenses: "", repository: "", publisher: "", licenseText: "" } : undefined },
    (err, out) => (err ? reject(err) : resolve(out)),
  ),
);

const failures = [];
const excepted = [];
for (const [id, info] of Object.entries(pkgs)) {
  const lic = Array.isArray(info.licenses) ? `(${info.licenses.join(" OR ")})` : String(info.licenses ?? "UNKNOWN");
  const name = id.slice(0, id.lastIndexOf("@"));
  const ex = findException(name);
  if (policy.denyPackages[name]) { failures.push(`${id}  [${lic}]  denied package: ${policy.denyPackages[name]}`); continue; }
  if (ex) {
    if (ex.license === lic) { excepted.push(`${id}  [${lic}]  exception: ${ex.reason}`); continue; }
    failures.push(`${id}  [${lic}]  exception is pinned to license "${ex.license}" — license changed, re-review`);
    continue;
  }
  if (denyRe.test(lic)) { failures.push(`${id}  [${lic}]  denied license`); continue; }
  if (!spdxAllowed(lic)) failures.push(`${id}  [${lic}]  not on allowlist`);
}
const present = new Set(Object.keys(pkgs).map((id) => id.slice(0, id.lastIndexOf("@"))));
const stale = [...exceptions.keys()].filter((k) => (k.endsWith("*") ? ![...present].some((n) => n.startsWith(k.slice(0, -1))) : !present.has(k)));

if (args.has("--notices")) {
  const lines = [
    "THIRD-PARTY NOTICES — Horizon Pulse",
    "",
    "This file lists the third-party npm packages in the production dependency",
    "tree of horizon-pulse, with their declared license and the license text",
    "shipped in each package. Generated by `npm run notices`",
    "(scripts/license-check.mjs, license-checker-rseidelsohn); do not edit by hand.",
    "Regenerate on Linux after any dependency change (platform-specific optional",
    "packages, e.g. @img/sharp-*, differ by OS).",
    "",
    `Packages: ${Object.keys(pkgs).length}`,
    "",
  ];
  for (const id of Object.keys(pkgs).sort()) {
    const p = pkgs[id];
    const lic = Array.isArray(p.licenses) ? p.licenses.join(" OR ") : p.licenses;
    lines.push("=".repeat(78), `${id}`, `License: ${lic}`);
    if (p.repository) lines.push(`Repository: ${p.repository}`);
    if (p.publisher) lines.push(`Publisher: ${p.publisher}`);
    lines.push("");
    lines.push(p.licenseText && p.licenseText.trim() ? p.licenseText.trim() : "(no license file shipped in the package; see the declared license above)");
    lines.push("");
  }
  writeFileSync(path.join(root, "THIRD-PARTY-NOTICES"), lines.join("\n") + "\n");
  console.log(`THIRD-PARTY-NOTICES written (${Object.keys(pkgs).length} production packages).`);
}

console.log(`license-check: ${Object.keys(pkgs).length} packages scanned (${production ? "production" : "production + dev"}).`);
if (excepted.length) console.log(`Documented exceptions (${excepted.length}):\n  ` + excepted.join("\n  "));
if (stale.length) console.log(`Note: exceptions not present in this tree (ok if dev-only or platform-specific): ${stale.join(", ")}`);
if (failures.length) {
  console.error(`\nLICENSE CHECK FAILED — ${failures.length} package(s):\n  ` + failures.join("\n  "));
  console.error("\nFix: remove the dependency, or add a pinned, reasoned exception to scripts/license-policy.json (needs review).");
  process.exit(1);
}
console.log("license-check: PASS");
