/**
 * Captures every unpaid 402 / discovery surface the site serves, as raw bytes.
 *
 * This file must stay runnable against origin/main unchanged (it imports only
 * route modules and public files that exist on main), because the golden
 * fixture tests/fixtures/x402-flag-off.golden.json is generated by running it
 * on a clean main checkout. See tests/x402-flag-off.test.ts.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { NextRequest } from "next/server";

export const PAID_ROUTES = [
  "pulse", "signals", "yield", "portfolio", "gas", "funding", "fetch",
  "http", "extract", "x402-check", "screenshot", "search", "pdf",
] as const;
const POST_ROUTES = new Set(["http", "extract"]);

export type Captured = { status: number; headers: [string, string][]; body: string };

async function snap(res: Response): Promise<Captured> {
  const headers = [...res.headers.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return { status: res.status, headers, body: await res.text() };
}

function req(route: string, method: string, kind: "json" | "browser"): NextRequest {
  const headers: Record<string, string> =
    kind === "json"
      ? { accept: "application/json" }
      : { accept: "text/html,application/xhtml+xml", "sec-fetch-mode": "navigate" };
  return new NextRequest(`https://horizonpulse.dev/api/${route}`, { method, headers });
}

type RouteModule = {
  GET: (r: NextRequest) => Promise<Response>;
  POST?: (r: NextRequest) => Promise<Response>;
  OPTIONS: () => Promise<Response>;
};

const ROOT = path.resolve(__dirname, "..", "..");

async function loadRoute(route: string): Promise<RouteModule> {
  return (await import(path.join(ROOT, "app", "api", route, "route.ts"))) as RouteModule;
}

/** Every route x {GET json, GET browser, POST json (http/extract), OPTIONS}. */
export async function captureRoutes(): Promise<Record<string, Captured>> {
  const out: Record<string, Captured> = {};
  for (const route of PAID_ROUTES) {
    const mod = await loadRoute(route);
    out[`GET /api/${route} json`] = await snap(await mod.GET(req(route, "GET", "json")));
    out[`GET /api/${route} browser`] = await snap(await mod.GET(req(route, "GET", "browser")));
    if (POST_ROUTES.has(route)) {
      out[`POST /api/${route} json`] = await snap(await mod.POST!(req(route, "POST", "json")));
    }
    out[`OPTIONS /api/${route}`] = await snap(await mod.OPTIONS());
  }
  return out;
}

const sha256 = (b: Buffer | string) => createHash("sha256").update(b).digest("hex");

/** Static + generated discovery docs: /.well-known/x402, openapi.json, llms.txt, skill.md. */
export async function captureDiscovery(): Promise<Record<string, Captured | string>> {
  const wk = (await import(path.join(ROOT, "app", ".well-known", "x402", "route.ts"))) as { GET: () => Response };
  const skill = (await import(path.join(ROOT, "app", "skill.md", "route.ts"))) as { GET: (...a: unknown[]) => Promise<Response> | Response };
  return {
    "GET /.well-known/x402": await snap(wk.GET()),
    "GET /skill.md": await snap(await skill.GET(new NextRequest("https://horizonpulse.dev/skill.md"))),
    "sha256 public/openapi.json": sha256(readFileSync(path.join(ROOT, "public", "openapi.json"))),
    "sha256 public/llms.txt": sha256(readFileSync(path.join(ROOT, "public", "llms.txt"))),
    "sha256 public/.well-known/x402list.txt": sha256(readFileSync(path.join(ROOT, "public", ".well-known", "x402list.txt"))),
  };
}

export const CDP_ENV = { CDP_API_KEY_ID: "test-key-id", CDP_API_KEY_SECRET: "test-key-secret" };
